[package]
name = "tests"
version = "0.0.0"
edition = "2021"

[dependencies]
fuels = { workspace = true }
tokio = { workspace = true }

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
